# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.cache/wt [current_project]
set_property parent.project_path C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/ip/blk_memB_gen_0/coe_files/coe_rom_b.coe
add_files C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/ip/blk_memB_gen_0/coe_files/coe_rom_b.coe
read_vhdl -library xil_defaultlib {
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/imports/lab1/lab1_parteA/lab1_parteA.srcs/sources_1/imports/new/FF_D.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/PowerOnReset.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/imports/lab1/lab1_parteC/lab1_parteC.srcs/sources_1/new/PowerOnReset.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/counter_3Bits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/imports/sources_1/imports/new/counter_Nbits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/imports/sources_1/new/divisor_frecuencia.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/lab2_FSM.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/lab2_ROM_generated.srcs/sources_1/new/lab2_ROM_gen.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/package_inf_rom.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/lab2_ROM_inf.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/new/lab2_comparador_salida.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/lab2_dual_port_ram_gen.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/new/lad2_bloque_sumador.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/imports/sources_1/imports/lab1/lab1_parteA/lab1_parteA.srcs/sources_1/imports/new/synchronizer.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/new/lab2_top_level_module.vhd
}
read_ip -quiet C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/ip/blk_memB_gen_0/blk_memB_gen_0.xci
set_property used_in_implementation false [get_files -all c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/ip/blk_memB_gen_0/blk_memB_gen_0_ooc.xdc]

read_ip -quiet C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_level_module/lab2_top_level_module.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab2_top_level_module -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab2_top_level_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab2_top_level_module_utilization_synth.rpt -pb lab2_top_level_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
