# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B.xci
# IP: The module: 'blk_mem_gen_0_ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0_ROM_B'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B.xci
# IP: The module: 'blk_mem_gen_0_ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0_ROM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
