# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard_master_XDC_RevC_D_v3.xdc

# IP: ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0_ROM_B || ORIG_REF_NAME==blk_mem_gen_0_ROM_B} -quiet] -quiet
