# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.cache/wt [current_project]
set_property parent.project_path C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/coe_rom/coe_rom_b.coe
read_vhdl -library xil_defaultlib {
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_comparador_salida/lab2_comparador_salida.srcs/sources_1/imports/lab1/lab1_parteA/lab1_parteA.srcs/sources_1/imports/new/FF_D.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_comparador_salida/lab2_comparador_salida.srcs/sources_1/imports/lab1/lab1_parteC/lab1_parteC.srcs/sources_1/new/PowerOnReset.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_reset_async_sync/lab2_reset_async_sync.srcs/sources_1/new/PowerOnReset.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/counter_3Bits/counter_3Bits.srcs/sources_1/new/counter_3Bits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_comparador_salida/lab2_comparador_salida.srcs/sources_1/imports/sources_1/imports/new/counter_Nbits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_comparador_salida/lab2_comparador_salida.srcs/sources_1/imports/sources_1/new/divisor_frecuencia.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_FSM/lab2_FSM.srcs/sources_1/new/lab2_FSM.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_ROM_inf/lab2_ROM_inf.srcs/sources_1/new/package_inf_rom.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_ROM_inf/lab2_ROM_inf.srcs/sources_1/new/lab2_ROM_inf.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/lab2_top_v3.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_bloque_sumador/lab2_bloque_sumador.srcs/sources_1/new/lad2_bloque_sumador.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/lab2/lab2_comparador_salida/lab2_comparador_salida.srcs/sources_1/imports/lab1/lab1_parteA/lab1_parteA.srcs/sources_1/imports/new/synchronizer.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/imports/new/lab2_comparador_salida.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/lab2_dual_port_ram_gen.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/lab2_ROM_gen.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/reg_8bits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/single_ram.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/debouncer.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/counter_22bits.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/FF_D_en.vhd
  C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/new/lab2_ROM_D_inf.vhd
}
read_ip -quiet C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B.xci
set_property used_in_implementation false [get_files -all c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_ROM_B/blk_mem_gen_0_ROM_B_ooc.xdc]

read_ip -quiet C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_RAM/blk_mem_gen_0_RAM.xci
set_property used_in_implementation false [get_files -all c:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/sources_1/ip/blk_mem_gen_0_RAM/blk_mem_gen_0_RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/constrs_1/new/zedboard_master_XDC_RevC_D_v3.xdc
set_property used_in_implementation false [get_files C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.srcs/constrs_1/new/zedboard_master_XDC_RevC_D_v3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab2_top_v3 -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab2_top_v3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab2_top_v3_utilization_synth.rpt -pb lab2_top_v3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
