webtalk_init -webtalk_dir C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.sim/sim_1/behav/xsim/xsim.dir/testbench_top_v3_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun 29 13:39:31 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6f870500-9c1a-4c88-ab0e-5cbea8a2493d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3e04436636c1492facfe197d84e4ae16" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "199" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "353.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1960598371 -regid "" -xml C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.sim/sim_1/behav/xsim/xsim.dir/testbench_top_v3_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.sim/sim_1/behav/xsim/xsim.dir/testbench_top_v3_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/xilinx_proyectos/Laboratorios/lab2/lab2_top_v3/lab2_top_v3.sim/sim_1/behav/xsim/xsim.dir/testbench_top_v3_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
